Controllers/BookController.cs
using LibraryApp.Models;
using LibraryApp.ViewModels;
using LibraryApp.Data;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using System.IO;
using Microsoft.Extensions.Hosting.Internal;
using Microsoft.AspNetCore.Hosting;

namespace LibraryApp.Controllers
{
    [Authorize]
    public class BookController : Controller
    {
        private BookDbContext context;

        //https://csharp-video-tutorials.blogspot.com/2019/05/file-upload-in-aspnet-core-mvc.html
        //https://www.youtube.com/watch?v=aoxEJii70_I&t=514s
        private readonly IHostingEnvironment hostingEnvironment;

        public BookController(BookDbContext dbContext, IHostingEnvironment hostingEnvironment)
        {
            context = dbContext;
            this.hostingEnvironment = hostingEnvironment;
        }

        [AllowAnonymous]
        public IActionResult Index()
        {
            List<Book> books = context.Books.ToList();
            return View(books);


        }

        public IActionResult Add()
        {
            AddBookViewModel addBookViewModel = new AddBookViewModel();
            return View(addBookViewModel);
        }

        [HttpPost("/Add")]
        public IActionResult ProcessAddBookForm(AddBookViewModel addBookViewModel)
        {
            if (ModelState.IsValid)
            {
                string uniqueFileName = null;

                if (addBookViewModel.Photo != null)
                {
                    // The image must be uploaded to the images folder in wwwroot
                    // To get the path of the wwwroot folder we are using the inject
                    // HostingEnvironment service provided by ASP.NET Core
                    string uploadsFolder = Path.Combine(hostingEnvironment.WebRootPath, "images");
                    // To make sure the file name is unique we are appending a new
                    // GUID value and and an underscore to the file name
                    uniqueFileName = Guid.NewGuid().ToString() + "_" + addBookViewModel.Photo.FileName;
                    string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                    // Use CopyTo() method provided by IFormFile interface to
                    // copy the file to wwwroot/images folder
                    addBookViewModel.Photo.CopyTo(new FileStream(filePath, FileMode.Create));
                }

                Book newBook = new Book
                {
                    Name = addBookViewModel.Name,
                    Description = addBookViewModel.Description,
                    ISBN = addBookViewModel.ISBN,
                    Category = addBookViewModel.Category.ToString(),
                    LibraryAddressStreet =addBookViewModel.LibraryAddressStreet,
                    LibraryAddressCity = addBookViewModel.LibraryAddressCity,
                    LibraryAddressState = addBookViewModel.LibraryAddressState,
                    LibraryAddressZip = addBookViewModel.LibraryAddressZip,
                    Latitude = addBookViewModel.Latitude,
                    Longitude = addBookViewModel.Longitude,
                    PhotoPath = uniqueFileName

                };

               // newBook.BarcodeNum = newBook.BarcodeNum;
                context.Books.Add(newBook);
                context.SaveChanges();

                return Redirect("/book");
            }
            return View("Add", addBookViewModel);
        }


        public IActionResult About(int id)
        {
            Book theBook = context.Books
                .Single(e => e.Id == id);

            return View(theBook);
        }




        public IActionResult Delete(int id)
        {
            Book theBook = context.Books
                .Single(e => e.Id == id);

            context.Books.Remove(theBook);
            context.SaveChanges();

            return Redirect("/book");


        }
        
        public IActionResult Edit(int id)
        {
            Book theBook = context.Books.Find(id);
            AddBookViewModel book = new AddBookViewModel
            { 
                Id = theBook.Id,
                Name = theBook.Name,
                Description = theBook.Description,
                ISBN = theBook.ISBN,
                //converts string to enum
                Category = (Category)Enum.Parse(typeof(Category), theBook.Category, true),
                LibraryAddressStreet = theBook.LibraryAddressStreet,
                LibraryAddressCity = theBook.LibraryAddressCity,
                LibraryAddressState = theBook.LibraryAddressState,
                LibraryAddressZip = theBook.LibraryAddressZip
            };
            
            return View(book);
        }

        [HttpPost("/Edit")]
        public IActionResult ProcessEdit(AddBookViewModel addBookViewModel)
        {
            Book theBook = context.Books.Find(addBookViewModel.Id);

            theBook.Name = addBookViewModel.Name;
            theBook.Description = addBookViewModel.Description;
            theBook.ISBN = addBookViewModel.ISBN;
            theBook.Category = addBookViewModel.Category.ToString();
            theBook.LibraryAddressStreet = addBookViewModel.LibraryAddressStreet;
            theBook.LibraryAddressCity = addBookViewModel.LibraryAddressCity;
            theBook.LibraryAddressState = addBookViewModel.LibraryAddressState;
            theBook.LibraryAddressZip = addBookViewModel.LibraryAddressZip;
            theBook.Longitude = addBookViewModel.Longitude;
            theBook.Latitude = addBookViewModel.Latitude;
                    
            context.Books.Update(theBook);
            context.SaveChanges();

            return Redirect("/book");
        }

    }
}

Controllers/SearchController.cs
using LibraryApp.Data;
using LibraryApp.Models;
using LibraryApp.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LibraryApp.Controllers
{
    [Authorize]
    public class SearchController : Controller
    {
        private BookDbContext context;

        public SearchController(BookDbContext dbContext)
        {
            context = dbContext;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Results(string searchTerm)
        {
            List<Book> books;
            List<BookDetailViewModel> displayBooks = new List<BookDetailViewModel>();

            if (string.IsNullOrEmpty(searchTerm))
            {
                books = context.Books
                   .ToList();

                foreach (var book in books)
                {
                    BookDetailViewModel newDisplayBook = new BookDetailViewModel(book);
                    displayBooks.Add(newDisplayBook);
                }
            }
            else
            {
                    /*books = context.Books
                        .Where(j => j.Name == searchTerm)
                        .ToList();*/
                books = context.Books
                        .Where(j => j.Name.ToLower().IndexOf(searchTerm.ToLower()) >= 0)
                        .ToList();

                foreach (Book book in books)
                    {
                        BookDetailViewModel newDisplayBook = new BookDetailViewModel(book);
                        displayBooks.Add(newDisplayBook);
                    }
            }
            ViewBag.books = displayBooks;

            return View("Index");
        }
    }
}

Controllers/SortController.cs
using LibraryApp.Data;
using LibraryApp.Models;
using LibraryApp.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LibraryApp.Controllers
{
    [Authorize]
    public class SortController : Controller
    {
        private BookDbContext context;

        public SortController(BookDbContext dbContext)
        {
            context = dbContext;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Sorted(int category)
        {
            List<Book> books = new List<Book>();
            List<BookDetailViewModel> displayBooks = new List<BookDetailViewModel>();
            /*switch (category)
            {
                case 0:
                    books = context.Books
                        .Where(js => js.Category == Category.Art.ToString())
                    .ToList();

                    foreach (var book in books)
                    {
                        BookDetailViewModel newDisplayBook = new BookDetailViewModel(book);
                        displayBooks.Add(newDisplayBook);
                    }
                    break;
                case 1:
                    books = context.Books
                        .Where(js => js.Category == Category.Biography.ToString())
                    .ToList();

                    foreach (var book in books)
                    {
                        BookDetailViewModel newDisplayBook = new BookDetailViewModel(book);
                        displayBooks.Add(newDisplayBook);
                    }
                    break;
                case 2:
                    books = context.Books
                        .Where(js => js.Category == Category.Business.ToString())
                    .ToList();

                    foreach (var book in books)
                    {
                        BookDetailViewModel newDisplayBook = new BookDetailViewModel(book);
                        displayBooks.Add(newDisplayBook);
                    }
                    break;
                case 3:
                    books = context.Books
                        .Where(js => js.Category == Category.Comics.ToString())
                    .ToList();

                    foreach (var book in books)
                    {
                        BookDetailViewModel newDisplayBook = new BookDetailViewModel(book);
                        displayBooks.Add(newDisplayBook);
                    }
                    break;
                case 4:
                    books = context.Books
                        .Where(js => js.Category == Category.Tech.ToString())
                    .ToList();

                    foreach (var book in books)
                    {
                        BookDetailViewModel newDisplayBook = new BookDetailViewModel(book);
                        displayBooks.Add(newDisplayBook);
                    }
                    break;
                case 5:
                    books = context.Books
                        .Where(js => js.Category == Category.Cooking.ToString())
                    .ToList();

                    foreach (var book in books)
                    {
                        BookDetailViewModel newDisplayBook = new BookDetailViewModel(book);
                        displayBooks.Add(newDisplayBook);
                    }
                    break;
                case 6:
                    books = context.Books
                        .Where(js => js.Category == Category.Education.ToString())
                    .ToList();

                    foreach (var book in books)
                    {
                        BookDetailViewModel newDisplayBook = new BookDetailViewModel(book);
                        displayBooks.Add(newDisplayBook);
                    }
                    break;
                case 7:
                    books = context.Books
                        .Where(js => js.Category == Category.History.ToString())
                    .ToList();

                    foreach (var book in books)
                    {
                        BookDetailViewModel newDisplayBook = new BookDetailViewModel(book);
                        displayBooks.Add(newDisplayBook);
                    }
                    break;
                case 8:
                    books = context.Books
                        .Where(js => js.Category == Category.Kids.ToString())
                    .ToList();

                    foreach (var book in books)
                    {
                        BookDetailViewModel newDisplayBook = new BookDetailViewModel(book);
                        displayBooks.Add(newDisplayBook);
                    }
                    break;
                case 9:
                    books = context.Books
                        .Where(js => js.Category == Category.Literature.ToString())
                    .ToList();

                    foreach (var book in books)
                    {
                        BookDetailViewModel newDisplayBook = new BookDetailViewModel(book);
                        displayBooks.Add(newDisplayBook);
                    }
                    break;
                case 10:
                    books = context.Books
                        .Where(js => js.Category == Category.Medical.ToString())
                    .ToList();

                    foreach (var book in books)
                    {
                        BookDetailViewModel newDisplayBook = new BookDetailViewModel(book);
                        displayBooks.Add(newDisplayBook);
                    }
                    break;
                case 11:
                    books = context.Books
                        .Where(js => js.Category == Category.ScienceFi.ToString())
                    .ToList();

                    foreach (var book in books)
                    {
                        BookDetailViewModel newDisplayBook = new BookDetailViewModel(book);
                        displayBooks.Add(newDisplayBook);
                    }
                    break;
                case 12:
                    books = context.Books
                        .Where(js => js.Category == Category.Travel.ToString())
                    .ToList();

                    foreach (var book in books)
                    {
                        BookDetailViewModel newDisplayBook = new BookDetailViewModel(book);
                        displayBooks.Add(newDisplayBook);
                    }
                    break;
            }*/

            books = context.Books
            .Where(js => js.Category == Enum.GetName(typeof(Category), category))
        .ToList();
            foreach (var book in books)
            {
                BookDetailViewModel newDisplayBook = new BookDetailViewModel(book);
                displayBooks.Add(newDisplayBook);
            }

            ViewBag.books = displayBooks;


            return View("Index");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LibraryApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-social/5.1.1/bootstrap-social.css" integrity="sha512-sopmFEmRVsWt542K+yzH3FQ1KJfdosOJG+bGLs9ZJT07b/3gUxRA9ICuJg2JtoZ9WeknAUuwJ0ggnmrV1YL6kQ==" crossorigin="anonymous" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3" style="background-color:gold">
            <div class="container" >
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Index">Inventory</a>
                        </li>

                        <li class="nav-item">

                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Add">Add a Book</a>

                        </li>
                        <li class="nav-item">

                            <a class="nav-link text-dark" asp-area="" asp-controller="Sort" asp-action="index">Filter</a>

                        </li>



                    </ul>
                    <ul class="navbar-nav align-content-center">
                        <li class="nav-item">
                            <form asp-controller="Search" asp-action="Results" method="post">
                                <div class="form-row">
                                    <input type="text" name="searchTerm" id="searchTerm" placeholder="Book name..." />
                                    <input class="btn btn-info btn-sm" type="submit" value="Search" />
                                </div>
                            </form>
                            @* <a class="nav-link text-dark" asp-area="" asp-controller="Search" asp-action="Index">Search Books</a>*@
                        </li>
                    </ul>
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <partial name="_LoginPartial" />
                        </li>
                    </ul>

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted" style="background-color:gold">
        <div class="container">
            &copy; 2021 - LibraryApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @*Extra bootstrap features*@
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    

    @*Font Awesome*@
    <script src="https://kit.fontawesome.com/c2fbc04410.js" crossorigin="anonymous"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>